import React, { useState } from 'react';
import { Alert, Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import type { ScreenProps } from '../../../navigation/routes';
import { AppHeader } from '../../../components/AppHeader';
import { BottomNav } from '../../../components/BottomNav';
import { colors, shadows } from '../../../theme/theme';

export default function DonationScreen({ navigation }: ScreenProps<'Donation'>) {
  const [gate, setGate] = useState(''); const [unlocked, setUnlocked] = useState(false); const [amount, setAmount] = useState('500'); const [method, setMethod] = useState('bKash');
  const unlock = () => { if (Number(gate) === 48) setUnlocked(true); else Alert.alert('সঠিক উত্তর দিন', '৮৭ − ৩৯ কত?'); };
  const donate = () => Alert.alert('Demo Donation Successful', `৳${amount || '0'} via ${method}\nধন্যবাদ শিশুদের শিক্ষাকে সহযোগিতা করার জন্য!`);
  return <SafeAreaView style={styles.safe}><View style={styles.page}><AppHeader title="সহযোগিতা করুন" onParentPress={() => navigation.navigate('AdultGate', { destination: 'parent' })} /><ScrollView contentContainerStyle={styles.content}>
    {!unlocked ? <View style={styles.gateCard}><Text style={styles.gateIcon}>👪</Text><Text style={styles.title}>Parent verification</Text><Text style={styles.message}>Payment option দেখার আগে বড়দের প্রশ্নটির উত্তর দিন।</Text><Text style={styles.question}>৮৭ − ৩৯ = ?</Text><TextInput value={gate} onChangeText={setGate} keyboardType="number-pad" style={styles.gateInput} /><Pressable style={styles.unlockButton} onPress={unlock}><Text style={styles.buttonText}>খুলুন</Text></Pressable></View> : <>
      <View style={styles.hero}><Image source={require('../../../../assets/images/tiger.png')} style={styles.tiger} /><Text style={styles.heroTitle}>সহযোগিতা করুন!</Text><Text style={styles.heroText}>আপনার স্বেচ্ছা সহযোগিতা server, content ও app maintenance-এ ব্যবহার হবে।</Text></View>
      <View style={styles.impact}><Text style={styles.cardTitle}>আপনার সহায়তার প্রভাব</Text><Text style={styles.line}>✓ নতুন interactive lesson তৈরি</Text><Text style={styles.line}>✓ শিশুদের জন্য ad-free learning</Text><Text style={styles.line}>✓ Server ও content maintenance</Text></View>
      <Text style={styles.section}>পরিমাণ নির্বাচন করুন</Text><View style={styles.amounts}>{['100', '500', '1000'].map((item) => <Pressable key={item} style={[styles.amount, amount === item && styles.selected]} onPress={() => setAmount(item)}><Text style={styles.amountText}>৳{item}</Text></Pressable>)}</View><TextInput value={amount} onChangeText={setAmount} keyboardType="number-pad" style={styles.custom} placeholder="Custom amount" />
      <Text style={styles.section}>Payment method</Text><View style={styles.methods}>{['bKash', 'Nagad', 'Rocket'].map((item) => <Pressable key={item} style={[styles.method, method === item && styles.selectedMethod]} onPress={() => setMethod(item)}><Text style={styles.methodText}>{item}</Text></Pressable>)}</View>
      <Pressable style={styles.donate} onPress={donate}><Text style={styles.donateText}>Demo Donate ৳{amount || '0'} ❤️</Text></Pressable><Text style={styles.disclaimer}>এটি university prototype। Real payment gateway সংযুক্ত নয়। Donation কোনো stars বা learning advantage দেয় না।</Text>
    </>}
  </ScrollView><BottomNav navigation={navigation} active="Donation" /></View></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, page: { flex: 1, padding: 10 }, content: { padding: 8, paddingBottom: 18 }, gateCard: { marginTop: 50, padding: 24, borderRadius: 24, backgroundColor: '#FFF', alignItems: 'center', ...shadows.card }, gateIcon: { fontSize: 55 }, title: { fontSize: 24, fontWeight: '900', color: colors.ink }, message: { marginTop: 7, textAlign: 'center', color: colors.muted, lineHeight: 20, fontWeight: '700' }, question: { marginTop: 20, fontSize: 30, fontWeight: '900', color: colors.greenDark }, gateInput: { width: 130, marginTop: 10, borderWidth: 2, borderColor: colors.border, borderRadius: 14, padding: 10, textAlign: 'center', fontSize: 20, fontWeight: '900' }, unlockButton: { marginTop: 12, backgroundColor: colors.orange, borderRadius: 15, paddingVertical: 12, paddingHorizontal: 30 }, buttonText: { color: '#FFF', fontWeight: '900' }, hero: { marginTop: 14, padding: 17, borderRadius: 22, alignItems: 'center', backgroundColor: colors.blue }, tiger: { width: 105, height: 105 }, heroTitle: { fontSize: 23, fontWeight: '900', color: '#FFF' }, heroText: { marginTop: 6, textAlign: 'center', lineHeight: 19, fontWeight: '700', color: '#F1FBFF' }, impact: { marginTop: 13, padding: 15, borderRadius: 20, backgroundColor: '#FFF', ...shadows.card }, cardTitle: { fontSize: 16, fontWeight: '900', color: colors.greenDark }, line: { marginTop: 8, fontWeight: '700', color: '#53606A' }, section: { marginTop: 18, marginBottom: 8, fontWeight: '900', color: colors.ink }, amounts: { flexDirection: 'row', gap: 9 }, amount: { flex: 1, padding: 13, borderRadius: 16, alignItems: 'center', backgroundColor: '#E8ECEF' }, selected: { backgroundColor: '#D9F8C4', borderWidth: 2, borderColor: colors.green }, amountText: { fontWeight: '900' }, custom: { marginTop: 9, borderWidth: 1, borderColor: colors.border, borderRadius: 15, padding: 12, backgroundColor: '#FFF', textAlign: 'center' }, methods: { flexDirection: 'row', gap: 9 }, method: { flex: 1, minHeight: 55, alignItems: 'center', justifyContent: 'center', borderRadius: 17, backgroundColor: '#FFF', borderWidth: 2, borderColor: colors.border }, selectedMethod: { borderColor: colors.green, backgroundColor: '#F0FFE7' }, methodText: { fontWeight: '900', fontSize: 12 }, donate: { marginTop: 18, backgroundColor: '#E90068', padding: 16, borderRadius: 20, alignItems: 'center' }, donateText: { color: '#FFF', fontWeight: '900', fontSize: 16 }, disclaimer: { marginTop: 10, fontSize: 10, lineHeight: 15, textAlign: 'center', color: colors.muted } });
