import { StyleSheet } from "react-native";

export const adminLiveStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#F3F6F8" },
  content: { padding: 16, paddingBottom: 36, maxWidth: 1100, width: "100%", alignSelf: "center" },
  loading: { flex: 1, alignItems: "center", justifyContent: "center", gap: 10 },
  loadingText: { fontWeight: "800", color: "#526777" },
  flex: { flex: 1 },
  header: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 12 },
  eyebrow: { fontSize: 9, letterSpacing: 1.4, fontWeight: "900", color: "#7D8A94" },
  title: { marginTop: 3, fontSize: 28, fontWeight: "900", color: "#173247" },
  meta: { marginTop: 3, fontSize: 10, fontWeight: "700", color: "#73818B" },
  roundButton: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF" },
  roundButtonText: { fontSize: 21, fontWeight: "900", color: "#315F85" },
  exitButton: { height: 42, paddingHorizontal: 14, borderRadius: 21, alignItems: "center", justifyContent: "center", backgroundColor: "#173247" },
  exitText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" },
  hero: { padding: 22, borderRadius: 28, backgroundColor: "#DDEBF5" },
  heroEyebrow: { fontSize: 9, letterSpacing: 1.4, fontWeight: "900", color: "#58778E" },
  heroTitle: { marginTop: 7, maxWidth: 600, fontSize: 28, lineHeight: 35, fontWeight: "900", color: "#1D4059" },
  heroText: { marginTop: 9, maxWidth: 620, fontSize: 11, lineHeight: 18, fontWeight: "700", color: "#587184" },
  updated: { marginTop: 8, fontSize: 9, fontWeight: "800", color: "#738998" },
  heading: { marginTop: 24, marginBottom: 10, fontSize: 19, fontWeight: "900", color: "#263F51" },
  headingRow: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between" },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
  metric: { width: "48.5%", padding: 14, borderRadius: 20, backgroundColor: "#FFFFFF" },
  metricIcon: { fontSize: 22 },
  metricValue: { marginTop: 7, fontSize: 25, fontWeight: "900", color: "#203B4E" },
  metricLabel: { marginTop: 2, fontSize: 10, fontWeight: "800", color: "#71808B" },
  progressCard: { marginBottom: 8, padding: 14, borderRadius: 18, backgroundColor: "#FFFFFF" },
  rowBetween: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  progressLabel: { fontSize: 11, fontWeight: "900", color: "#425968" },
  progressValue: { fontSize: 13, fontWeight: "900", color: "#315F85" },
  track: { height: 7, marginTop: 9, overflow: "hidden", borderRadius: 4, backgroundColor: "#E8EEF2" },
  fillBar: { height: "100%", borderRadius: 4, backgroundColor: "#648EAD" },
  warning: { marginTop: 4, padding: 14, borderRadius: 18, backgroundColor: "#FFF3D5" },
  warningTitle: { fontSize: 11, fontWeight: "900", color: "#735A1F" },
  warningText: { marginTop: 4, fontSize: 9, lineHeight: 15, fontWeight: "700", color: "#8B7540" },
  classRow: { flexDirection: "row", gap: 8 },
  classCard: { flex: 1, padding: 13, borderRadius: 18, backgroundColor: "#FFFFFF" },
  classLabel: { fontSize: 9, fontWeight: "900", color: "#75838D" },
  classValue: { marginTop: 5, fontSize: 23, fontWeight: "900", color: "#223E51" },
  small: { marginTop: 2, fontSize: 8, fontWeight: "700", color: "#929EA5" },
  panel: { padding: 13, borderRadius: 20, backgroundColor: "#FFFFFF", gap: 10 },
  subjectLabel: { fontSize: 11, fontWeight: "900", color: "#425866" },
  chapterRow: { flexDirection: "row", alignItems: "center", gap: 10, minHeight: 58, paddingVertical: 6 },
  numberBox: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#E4EFF6" },
  numberText: { fontSize: 16, fontWeight: "900", color: "#315F85" },
  chapterTitle: { fontSize: 11, fontWeight: "900", color: "#344D5F" },
  open: { fontSize: 9, fontWeight: "900", color: "#315F85" },
});
