import { StyleSheet } from "react-native";

export const teacherEditorStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#F3F6F8" },
  page: { flex: 1, backgroundColor: "#F3F6F8" },
  content: {
    width: "100%",
    maxWidth: 980,
    alignSelf: "center",
    padding: 16,
    paddingBottom: 36,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
  },
  back: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  backText: { fontSize: 28, color: "#264459" },
  flex: { flex: 1 },
  eyebrow: {
    fontSize: 8,
    letterSpacing: 1.2,
    fontWeight: "900",
    color: "#7C8B95",
  },
  title: {
    marginTop: 3,
    fontSize: 22,
    fontWeight: "900",
    color: "#244257",
  },
  subtitle: {
    marginTop: 3,
    fontSize: 9,
    fontWeight: "700",
    color: "#81909A",
  },
  add: {
    minHeight: 42,
    paddingHorizontal: 14,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#315F85",
  },
  addText: { color: "#FFFFFF", fontSize: 10, fontWeight: "900" },
  hero: {
    padding: 18,
    borderRadius: 24,
    backgroundColor: "#E3EEF6",
    marginBottom: 14,
  },
  heroTitle: { fontSize: 19, fontWeight: "900", color: "#294B63" },
  heroText: {
    marginTop: 5,
    fontSize: 10,
    lineHeight: 16,
    fontWeight: "700",
    color: "#658093",
  },
  list: { gap: 10 },
  card: {
    padding: 14,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  order: {
    width: 42,
    height: 42,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E6F0F6",
  },
  orderText: { fontSize: 15, fontWeight: "900", color: "#315F85" },
  cardTitle: { fontSize: 12, fontWeight: "900", color: "#344F61" },
  cardMeta: {
    marginTop: 3,
    fontSize: 9,
    fontWeight: "700",
    color: "#82909A",
  },
  summary: {
    marginTop: 10,
    padding: 10,
    borderRadius: 13,
    backgroundColor: "#F6F8FA",
    fontSize: 9,
    fontWeight: "700",
    color: "#647785",
  },
  actions: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 10 },
  action: {
    minHeight: 36,
    paddingHorizontal: 11,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E6EFF5",
  },
  actionText: { fontSize: 9, fontWeight: "900", color: "#315F85" },
  danger: { backgroundColor: "#FCE8E5" },
  dangerText: { color: "#A24F43" },
  empty: { padding: 28, alignItems: "center" },
  emptyTitle: { fontSize: 13, fontWeight: "900", color: "#506674" },
  emptyText: {
    marginTop: 5,
    textAlign: "center",
    fontSize: 9,
    lineHeight: 15,
    fontWeight: "700",
    color: "#8A979F",
  },
  loading: { flex: 1, alignItems: "center", justifyContent: "center", gap: 8 },
  modalBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(22,35,45,0.45)",
  },
  modal: {
    maxHeight: "94%",
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    backgroundColor: "#F5F7F9",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E7EB",
  },
  modalTitle: { fontSize: 18, fontWeight: "900", color: "#29485D" },
  close: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E7ECEF",
  },
  closeText: { fontSize: 22, color: "#536A78" },
  formContent: { padding: 16, paddingBottom: 28, gap: 13 },
  label: { fontSize: 10, fontWeight: "900", color: "#4B5F6D" },
  input: {
    minHeight: 46,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#DDE4E9",
    color: "#263F50",
    fontSize: 12,
    fontWeight: "700",
  },
  area: { minHeight: 78, textAlignVertical: "top" },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
  chip: {
    minHeight: 36,
    paddingHorizontal: 11,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E7ECEF",
  },
  chipActive: { backgroundColor: "#315F85" },
  chipText: { fontSize: 9, fontWeight: "900", color: "#647682" },
  chipTextActive: { color: "#FFFFFF" },
  footer: {
    flexDirection: "row",
    gap: 8,
    padding: 14,
    borderTopWidth: 1,
    borderTopColor: "#E2E7EB",
    backgroundColor: "#FFFFFF",
  },
  cancel: {
    flex: 1,
    minHeight: 48,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E9EDF0",
  },
  cancelText: { fontSize: 10, fontWeight: "900", color: "#5B6D79" },
  save: {
    flex: 2,
    minHeight: 48,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#315F85",
  },
  saveText: { fontSize: 10, fontWeight: "900", color: "#FFFFFF" },
});
