import React from 'react';
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { ScreenProps } from '../../../navigation/routes';
import { colors, shadows } from '../../../theme/theme';

export default function AdminDashboardScreen({ navigation }: ScreenProps<'AdminDashboard'>) {
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><View style={styles.header}><View><Text style={styles.title}>Admin Dashboard</Text><Text style={styles.subtitle}>University prototype control panel</Text></View><Pressable onPress={() => navigation.navigate('Subjects')}><Text style={styles.close}>Exit</Text></Pressable></View>
    <View style={styles.grid}><Metric color={colors.blue} icon="👥" value="12,450" label="Total Students" /><Metric color={colors.green} icon="📚" value="05" label="Published Chapters" /><Metric color={colors.orange} icon="৳" value="45.2K" label="Demo Donations" /><Metric color={colors.yellow} icon="⚡" value="98%" label="System Health" /></View>
    <View style={styles.card}><Text style={styles.cardTitle}>Content Management</Text>{['Class 1 · Bangla · আমার পরিবার', 'Class 1 · English · Letters', 'Class 1 · Math · ১ থেকে ১০'].map((item, index) => <View key={item} style={styles.contentRow}><View style={[styles.number, { backgroundColor: [colors.blue, colors.green, colors.orange][index] }]}><Text style={styles.numberText}>{index + 1}</Text></View><Text style={styles.contentName}>{item}</Text><Pressable onPress={() => Alert.alert('Demo', 'Publish/unpublish action recorded in prototype.')}><Text style={styles.action}>Edit</Text></Pressable></View>)}</View>
    <View style={styles.card}><Text style={styles.cardTitle}>Recent Activity</Text><Text style={styles.activity}>• 18 students completed a chapter</Text><Text style={styles.activity}>• 3 parent accounts linked children</Text><Text style={styles.activity}>• 5 demo donations recorded</Text></View>
    <View style={styles.alert}><Text style={styles.alertTitle}>System Alert</Text><Text style={styles.alertText}>Production version must validate admin roles, scores and payments on the backend.</Text></View>
  </ScrollView></SafeAreaView>;
}
function Metric({ color, icon, value, label }: { color: string; icon: string; value: string; label: string }) { return <View style={[styles.metric, { backgroundColor: color }]}><Text style={styles.metricIcon}>{icon}</Text><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#EDF3F6' }, page: { padding: 16, paddingBottom: 30 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { fontSize: 27, fontWeight: '900', color: '#15324A' }, subtitle: { color: colors.muted, fontWeight: '700' }, close: { color: colors.red, fontWeight: '900' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 18 }, metric: { width: '47%', minHeight: 125, borderRadius: 22, padding: 15, ...shadows.card }, metricIcon: { fontSize: 25 }, metricValue: { marginTop: 8, fontSize: 25, fontWeight: '900', color: '#183041' }, metricLabel: { fontSize: 11, fontWeight: '800', color: '#29485C' }, card: { marginTop: 15, padding: 16, borderRadius: 20, backgroundColor: '#FFF', ...shadows.card }, cardTitle: { fontSize: 17, fontWeight: '900', color: '#15324A' }, contentRow: { minHeight: 55, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#E8EDF0' }, number: { width: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, numberText: { fontWeight: '900' }, contentName: { flex: 1, marginLeft: 9, fontSize: 12, fontWeight: '800' }, action: { color: '#126D90', fontWeight: '900' }, activity: { marginTop: 10, color: '#53606A', fontWeight: '700' }, alert: { marginTop: 15, padding: 15, borderRadius: 18, backgroundColor: '#FFE1E1', borderWidth: 1, borderColor: colors.red }, alertTitle: { color: '#A32020', fontWeight: '900' }, alertText: { marginTop: 4, color: '#8A3030', lineHeight: 19, fontWeight: '700' } });
